apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bwuz2tnqp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bwuz2tnqp-nodejs 
  name: bwuz2tnqp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bwuz2tnqp-nodejs 
